### PR TITLE
Mode switch

### PR DESCRIPTION
**Pull request by isZumpo**
This is a big one. It includes all socket communication for the moment.

### CODE REVIEW

**Comment by isZumpo** [comment]
Ooh btw. Ignore the android code. It will be replaced soon by another branch anyhow.

**Review by konglobemeralt — APPROVED** [review]
Looks good.

**Comment by emiljanQ3** [comment]
Please do some functional decomposition in the places we discussed during our code review meeting in Linsen.

**Comment by Hugormen** [comment]
༼ つ ◕_◕ ༽つ PLEASE DO FUNCTIONAL DECOMPOSITION HAPMUS ༼ つ ◕_◕ ༽つ

**Comment by isZumpo** [comment]
#  **(╯°□°）╯︵ ┻━┻** 
Alright it's done now mate!

**Review by emiljanQ3 — APPROVED** [review]
SÅ jävla bra!

**Review by Hugormen — APPROVED** [review]
Wowowow, this was gr8

**Pull request merged**
